//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse_prod_PurchOrd
    {
        public string W_name { get; set; }
        public int Prod_id { get; set; }
        public int Po_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> production_date { get; set; }
        public Nullable<int> Expiration_Dur { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual PurchasingOrder PurchasingOrder { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
